### ISSUE TITLE
Page Heros

### ISSUE THREAD

**Issue by antaratma** [unaio/una#5]
The correct name for what we now call a "Page Cover" is "Page Hero. So, we need to rename it and improve as follows:

- [ ] In Designer add a setting for "Min Page Hero height", which can be set in px, rem or vh. By default set to 40vh.

- [ ] In Designer, add a setting for Page Hero text style. CSS style for color, shadow, size and font face.

- [ ] Im Designer, add "Upload cover layer image" form for alternative gradient/darkening/brightening cover. 

- [ ]  **Start from top** checkbox (positioning the Page Hero at the top of the page, instead of starting where header ends. The top part of the hero should then be underneath the header.

- [ ] The picture for Page Hero is called "Hero Image". When we upload one via Designer, it should support retina/@2 resolution.

- [ ] In Page Builder we can now upload individual Hero Images for some pages. Along with upload this settings sections should add a few more options:

1. **Minimum Page Hero height** (overriding global setting).
---- this is needed for pages like Homepage or Post or Article or Profile, where hero needs to be large and should display all of the uploaded Hero Image height. 

2. **Content** - raw / HTML input with language switcher and upload image form, allowing to input any custom content and styles overriding default ones.  This is needed for pages like homepage, where cover layer may not be needed, or some special scroller, video or effects must be added. By default, fill it with code that is rendered by default settings from Designer.
